---
# Codacy configuration file for gla-BoostTicketing
# See: https://docs.codacy.com/repositories-configure/codacy-configuration-file/
# Exclude files and directories from analysis
exclude_paths:
  # Test directories - using wildcards
  - "**/*.Tests/**"
  - "**/*Test/**"
  - "**/tests/**"
  - "**/test/**"
  - "**/__tests__/**"
  - "**/*.test.*"
  - "**/*.spec.*"
  # IDE and editor directories
  - ".github/**"
  - ".vscode/**"
  - ".idea/**"
  - ".vs/**"
  # Build and output directories
  - "**/obj/**"
  - "**/bin/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/wwwroot/**"
  - "**/out/**"
  # Database migrations
  - "**/migrations/**"
  - "**/Migrations/**"
  # Version control
  - ".git/**"
  # Node.js dependencies and package files
  - "**/node_modules/**"
  - "**/packages/**"
  - "package-lock.json"
  - "yarn.lock"
  # Coverage and analysis output
  - "**/coverage/**"
  - "**/TestResults/**"
  - "**/*.coverage"
  - "**/*.coveragexml"
  # Client app build artifacts
  - "**/ClientApp/build/**"
  - "**/ClientApp/dist/**"
  # ASP.NET Core specific
  - "**/App_Data/**"
  - "**/logs/**"
  # Configuration and generated files
  - "**/*.generated.*"
  - "**/appsettings.*.json"
  - "**/web.config"
  # Documentation
  - "**/*.md"
  - "**/docs/**"
    # OS generated files
  - ".DS_Store"
  - "Thumbs.db"
  # Temporary files
  - "**/*.tmp"
  - "**/*.temp"
  - "**/*.log"
  # .NET specific tools can be configured here if needed
  # Example:
  # roslynator:
  #   enabled: true
