engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript
        - python
        - java
        - ruby
  fixme:
    enabled: true
  phpmd:
    enabled: true
  pmd:
    enabled: true
  pylint:
    enabled: true
  rubocop:
    enabled: true
  shellcheck:
    enabled: true
  sonar:
    enabled: true
  stylelint:
    enabled: true
  tslint:
    enabled: true

exclude_paths:
  - "**/node_modules/**"
  - "**/vendor/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/coverage/**"
  - "**/test/**"
  - "**/tests/**"
  - "**/spec/**"
  - "**/docs/**" 
